### ISSUE TITLE
More than one record found in handle error

### ISSUE THREAD

**Issue by abrusell** [hotsnow-sean/OTSUCNV#1]
I'm not sure I've understood how to launch it:
```
$ python run_single.py prob_markdup.bam chr1 Homo_sapiens_assembly38.fasta
Traceback (most recent call last):
  File "/tools/OTSUCNV/run_single.py", line 18, in <module>
    data = binning(args.bam, {args.contig: args.fa})
  File "/tools/OTSUCNV/binning.py", line 72, in binning
    fasta = SeqIO.read(fasta, "fasta").seq
  File "/home/user/mambaforge/lib/python3.9/site-packages/Bio/SeqIO/__init__.py", line 667, in read
    raise ValueError("More than one record found in handle")
ValueError: More than one record found in handle
```

Why this error?

**Comment by hotsnow-sean** [comment]
The program use the `SeqIO.read` method from the `biopython` library to read FASTA files. It assumes that the input file contains only one record.
To address this issue, you can provide a FASTA file that contains only the sequence for chr1, instead of passing a file with multiple records. Alternatively, you can modify the logic for reading the FASTA file to meet your specific requirements.
